# -*- coding: utf-8 -*-
"""SMA Crossover Strategy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nrxa3bZbihEg3xSused7uoWZ4jaWvNEV
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from os import close

ticker = "AAPL"
data = yf.download(ticker, start='2020-01-01', end='2024-12-31')
data = data[["Close"]]
data.dropna(inplace=True)

data["SMA50"] =  data["Close"].rolling(50).mean()
data["SMA200"] =  data["Close"].rolling(200).mean()

data['Signal'] = 0
data['Signal'][50:] = np.where(data['SMA50'][50:] > data['SMA200'][50:], 1, 0)
data['Position'] = data['Signal'].diff()

plt.figure(figsize=(14, 8))
plt.plot(data['Close'], label='Close Price', alpha=0.5)
plt.plot(data['SMA50'], label='SMA50', alpha=0.75)
plt.plot(data['SMA200'], label='SMA200', alpha=0.75)

# Buy signal
plt.plot(data[data['Position'] == 1].index,
         data['SMA50'][data['Position'] == 1],
         '^', markersize=12, color='g', label='Buy Signal')

# Sell signal
plt.plot(data[data['Position'] == -1].index,
         data['SMA50'][data['Position'] == -1],
         'v', markersize=12, color='r', label='Sell Signal')

plt.title(f'{ticker} SMA Crossover Strategy')
plt.xlabel('Date')
plt.ylabel('Price ($)')
plt.legend()
plt.grid()
plt.show()

data['Returns'] = data['Close'].pct_change()
data['Strategy_Returns'] = data['Returns'] * data['Signal'].shift(1)

# Cumulative returns
data[['Returns', 'Strategy_Returns']].cumsum().apply(np.exp).plot(figsize=(14, 6))
plt.title("Cumulative Market vs Strategy Returns")
plt.grid()
plt.show()